# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Deploy a Website
email: example@email.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the sample Jekyll-generate site created in Codecademy's Deploy a Website course!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://facemail.org" # the base hostname & protocol for your site
twitter_username: codecademy

# Build settings
markdown: kramdown
